#
# Containerised caddy.
#
# Note: Duet o use network_mode: host this Caddy container does not work on macOS.
#
version: '3'
services:
  # https://hub.docker.com/_/caddy
  # https://caddyserver.com/docs/quick-starts/reverse-proxy
  # Running Caddy as command
  caddy:
    image: caddy:v2.4.5
    container_name: caddy
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: caddy run -config /etc/caddy/Caddyfile
    environment:
      ACME_AGREE: "true"
    # We directly bind to the host ports and there is no Docker network here
    network_mode: host
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/data:/data
      - $PWD/data/config:/config
      - $PWD/index.html:/usr/share/caddy/index.html
      - $PWD/logs:/var/log/caddy # shared volume with caddy
      - /home/docs/html:/docs  # For docs static hosting
  # Logstash logging for caddy from Json logs
  caddy-logstash:
    image: logstash:8.2.0
    container_name: caddy-logstash
    network_mode: host
    environment:
      # elastisearch login vars
      ECS_SERVER: ${ECS_SERVER}
      ECS_USER: ${ECS_USER}
      ECS_PASSWORD: ${ECS_PASSWORD}
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
      - $PWD/logs:/data/logs #shared volume
    depends_on:
      - caddy
