#
# Containerised caddy.
#
# Note: Duet o use network_mode: host this Caddy container does not work on macOS.
#
version: '3'
services:
  # https://hub.docker.com/_/caddy
  # https://caddyserver.com/docs/quick-starts/reverse-proxy
  # Running Caddy as command
  caddy:
    image: caddy:v2.4.5
    container_name: caddy
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: caddy run -config /etc/caddy/Caddyfile
    environment:
      ACME_AGREE: "true"
    # We directly bind to the host ports and there is no Docker network here
    network_mode: host
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      # - $PWD/srv:/srv
      - $PWD/data:/data
      - $PWD/data/config:/config
      - $PWD/index.html:/usr/share/caddy/index.html
      - $PWD/logs:/var/log/caddy
  logstash-logger:
    image: logstash:7.5.2
    environment:
      ECS_SERVER: ${ECS_SERVER}
      ECS_USER: ${ECS_USER}
      ECS_PASSWORD: ${ECS_PASSWORD}
    network_mode: host
    volumes:
      - $PWD/logs:/logs
      - $PWD/data/config/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    command: logstash -f /config-dir/logstash01.conf
    depends_on:
    - caddy
