http.host: 0.0.0.0
log.level: info
xpack.monitoring.elasticsearch.hosts:
- https://${ECS_SERVER}:9200
xpack.monitoring.elasticsearch.password: ${ECS_PASSWORD}
xpack.monitoring.elasticsearch.username: ${ECS_USER}
xpack.monitoring.enabled: true
